name: Publish to NPM
run-name: ${{ github.actor }} is publishing to NPM 🚀

on:
  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        description: Dry run
        required: false
        default: false
      checkVersion:
        type: boolean
        description: Check version and publish accordingly to package.json version mod
        required: false
        default: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 18.10.0
      - run: yarn install
      - run: yarn build
      - uses: JS-DevTools/npm-publish@0f451a94170d1699fd50710966d48fb26194d939 # v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: package.json
          check-version: ${{ github.event.inputs.checkVersion == 'true'}}
          dry-run: ${{ github.event.inputs.dryRun == 'true'}}
