name: Publish to NPM
run-name: ${{ github.actor }} is publishing to NPM 🚀

on:
  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        description: Dry run
        required: false
        default: false
      checkVersion:
        type: boolean
        description: Check version and publish accordingly to package.json version mod
        required: false
        default: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install
      - run: yarn build
      - run: cp package.json ./dist
      - run: cp README.md ./dist
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: dist/package.json
          access: public
          check-version: ${{ github.event.inputs.checkVersion == 'true'}}
          dry-run: ${{ github.event.inputs.dryRun == 'true'}}
